Feature/moneymong 493 회원가입 대학정보없음
MONEYMONG/Android-Moneymong pull request #22
Opened 2024-08-07 13:43 UTC by eunseo0105

## 요약
회원가입 시 대학정보 없음 로직을 추가 구현하였습니다🫠

## 작업내용
|회원가입 (대학 정보 없음) | 
|:----:|
| [회원가입 동영상](https://github.com/user-attachments/assets/e5371ec5-2110-403e-b1ee-6495a19471b6) | 

## 기타
- 대학정보없음 요건 추가로 schoolInfoExist라는 네이밍으로 판별하기 어려워 **schoolInfoProvided**라는 네이밍으로 변경하였습니다. 
- 추후 서버에서  schoolInfoExist 필드는 삭제 예정이라 **schoolInfoProvided** 필드로 로직을 변경하였습니다. 
- `TokenRequest(type.name, accessToken, "", "")` "" 값은 ios 로그인을 위하여 있는 형식이므로 빈 문자열로 요청 보냅니다.

2024-08-10 13:00 UTC, jhg3410 requested changes
고생하셨습니다!🙂

2024-08-10 13:00 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
>                  .align(Alignment.BottomCenter)
`Column` 의 content Composable 이 한 개(`SignUpButtonView`)라 `Box` 로 해도 동일하게 나옵니다!

2024-08-10 13:00 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpButtonView.kt
> +            )
`Text` 아래에 `Spacer` 가 없는데, 실제로 실행하면 여백이 존재하는 걸 확인했는데요!

그게 아래 이미지의 **SignUpScreen.kt** 의 76번째 줄 때문이라서, 
![image](https://github.com/user-attachments/assets/574dd6a7-4c4c-4e68-96f4-da82aeb9b0f7)

`.padding(horizontal = MMHorizontalSpacing)`로 변경한 다음, 
위 아래 여백을 다시 디자인대로 지정하면 될 것 같슴다!

2024-08-10 13:00 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/SignUpViewModel.kt
>          }
```kotlin
viewModelScope.launch {
    schoolInfoUseCase.invoke(infoExist)
}
```
    

`viewModelScope.launch` 로 바꿔주시면 감사하겠습니다. 
그리고 `schoolInfoUseCase` 는 data layer 에서 `preferences DataStore` 를 사용하는데, `preferences DataStore` 는 내부적으로 Dispatcher 를 IO 로 바꿔줘서 명시하지 않아도 됩니다!

> https://developer.android.com/codelabs/android-preferences-datastore#3

![image](https://github.com/user-attachments/assets/dd6580d5-b46e-403a-9071-79a3b7e45a66)

2024-08-11 11:29 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
>                  .align(Alignment.BottomCenter)
앗 이부분 대학정보없음을 여기에 추가했다가 하위 컴포저블로 이동하면서 수정이 안됐네용 수정하겠슴당!~

2024-08-11 18:21 UTC, jhg3410 approved these changes
확인했습니다!~🙂

2024-08-12 12:35 UTC, merged